<Log>:
    cols: 1
    problem_label: problem_label
    answer_layout: answer_layout

    Label:
        size_hint: 1, 0.3
        text: 'What could x represent?'
        font_size: 20

    Label:
        id: problem_label
        markup: True
        text: 'problem text'
        font_size: 30

    GridLayout:
        id: answer_layout
        size_hint: 1, 0.3
        rows: 1
